{
 "title": "File Storage Metriken",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Durchschnittliche Upload-Latenz (ms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(socket_io_latency_sum{operation=\"upload\"}[10m]) / rate(socket_io_latency_count{operation=\"upload\"}[10m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend-Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    { "expr": "frontend_health", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Durchschnittliche Delete-Latenz (ms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(socket_io_latency_sum{operation=\"delete\"}[10m]) / rate(socket_io_latency_count{operation=\"delete\"}[10m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend-Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    { "expr": "backend_health", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Database-Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    { "expr": "database_health", "legendFormat": "__auto" }
   ]
  }
 ]
}